config/routes.rb
Tefeci::Application.routes.draw do
  resources :credits

  
  
  
  resources :users

  resources :friends

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/tweets" => "tweets#create", :as => :create
  match "/friends/:id/email" => "friends#email", :as => :email
  match "/odenen/index" => "odenen#index"
  match "/odenmeyen/index" => "odenmeyen#index"
root :to => "home#index"

end

app/models/friend.rb
# -*- coding:utf-8 -*-
class Friend < ActiveRecord::Base
  belongs_to  :user
  has_many  :credits
  accepts_nested_attributes_for :credits
  validates_presence_of :name, :message => ':isim alani gereklidir.'
  validates_presence_of :email, :message => ':email alani  gereklidir.'
  validates_format_of     :email,
                          :with       => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i,
                          :message    => ':Gecerli bir email giriniz (tefeci@example.com)'

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # GET /friends
  # GET /friends.json
before_filter :login_required


  
  def index

    @friends = Friend.find_all_by_user_id(current_user.uid)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @friends }
    end
  end

  # GET /friends/1
  # GET /friends/1.json
   def show


    @credit=Credit.find_all_by_friend_id(params[:id])
    @friend = Friend.find_by_id_and_user_id(params[:id],current_user.uid) #bugfix login olan herkes herkesin arkadasini goremez
    respond_to do |format|
      format.html
      format.json { render :json => @friend }
    end
  end




  # GET /friends/new
  # GET /friends/new.json
  def new
    @friend = Friend.new(:user_id =>current_user.uid)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find_by_id_and_user_id(params[:id],current_user.uid)#bugfix login olan herkes herkesin arkadasini goremez
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(params[:friend])

    respond_to do |format|
      if @friend.save
        
        format.html { redirect_to @friend }
        format.json { render :json => @friend, :status => :created, :location => @friend }
      else
        format.html { render :action => "new" }
        format.json { render :json => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.json
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to @friend }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  def email
    @friend = Friend.find(params[:id])

    UserMailer.credit_confirmation(@friend).deliver
     respond_to do |format|
      format.html { redirect_to @friend}
      format.json { head :no_content }
    end
    
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy

    @credit = Credit.find_all_by_friend_id(params[:id])
    
    @friend = Friend.find(params[:id])

   @credit.each do |credit|
      credit.destroy
   end
    @friend.destroy
    

    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :Kullanici_No %><br />
    <%= f.text_field :user_id ,:readonly=>'true' %>
  </div>
  <div class="field">
    <%= f.label :Adi %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Soyadi %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="actions">
    <%= f.submit(label='Kaydet') %>

  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="wrapper col5">
  <div id="footer">
    <h2>Arkadas Duzenle</h2>
<%= render 'form' %>
<p>&nbsp;</p>

<p align="center">
<%= link_to '<<Vazgec', @friend %> 
</p>
</div></div>

app/views/friends/email.html.erb
<%= UserMailer.credit_confirmation(@friend).deliver%>

app/views/friends/index.html.erb
<div class="wrapper col5">
  <div id="footer">
    <h2>Arkadaslarim</h2>
    <table summary="Summary Here" cellpadding="0" cellspacing="0">
      <thead>
        <tr>
          <th>Adi</th>
          <th>Soyadi</th>
          <th>Email</th>
          <th colspan="2">Islemler</th>
        </tr>
      </thead>
     <%a=1%>
     <tbody>
        <% @friends.each do |friend| %>
 
        
        <%if a==1%>
        <tr class="light">
          <%a=0%>
          <%else%>
          <tr class="dark">
            <%a=1%>
            <%end%>
          <td><%= friend.name.upcase %></td>
          <td><%= friend.surname.upcase %></td>
          <td><%= friend.email %></td>
          <td><p align="center"><%= link_to 'BORC BILGISI', friend %></p></td>
          <td><p align="center"> <%= link_to 'KISIYI DUZENLE', edit_friend_path(friend) %></p></td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <br class="clear" />
    <h3><%= link_to '+ Yeni Arkadas Ekle', new_friend_path %></h3>
  </div>
</div>

app/views/friends/new.html.erb
<div class="wrapper col5">
  <div id="footer">

<h2>Yeni Arkadas Ekle</h2>

<%= render 'form' %>

<p align="center">
<%= link_to '<<Vazgec', @friend %>
</p></div></div>

app/views/friends/show.html.erb
<div class="wrapper col3"></div>
<div class="wrapper col4">
  <div id="container">
    <div id="content">
      <%@borc= Credit.sum('miktar',:group =>:friend_id,:conditions=>["durum='not_paid'"])[@friend.id] or 0 %>
      <h2>Kisi Bilgileri</h2>
     <h3>Adi : <%= @friend.name.upcase %>
       <p>Soyad : <%= @friend.surname.upcase %></p>
      <p>Email : <%= @friend.email %></p></h3>
      <p>Toplam Borcu : <% if @borc %> 
                        <%=@borc %>TL</h3>
                        <% else %>
                        0 TL</h3>
                        <% end %>    </p>
    </div>
    <div id="column">
      <div class="flickrbox">
        <h2 class="title">ISLEMLER        </h2>
        <ul>
          <li>Kisi Duzenle<a href="<%= edit_friend_path(@friend)%>"><img src="../../images/edit.jpg" alt="" width="65" height="65" alt="edit_friend"/></a></li>
          <li><%= link_to 'KISIYI SIL', @friend, :confirm => 'Kisiyi silerek bu kisinin tum borclarini da sileceksiniz. Emin misiniz? ', :method => :delete %><img src="../images/delete.jpg" alt="" width="65" height="65" /></a></li>
          <li>Yeni Borc<a href="<%= new_credit_path(:friend_id => @friend)%>" ><img src="../../images/add.jpg" alt="yeni_borc" width="65" height="65" /></a></li>
          <li>Email At<a href="<%= email_path(@friend)%>"><img src="../../images/mail1.png" alt="send_email" width="65" height="65" /></a></li>
          <li class="last">Tweet At<a href="<%= create_path(:tweet =>  "#{@friend.name.upcase} #{@friend.surname.upcase}'n bana #{@borc} TL borcu var ve odemiyor :(" )%>" ><img src="../../images/twitter.png" alt="send_tweet" width="65" height="65" /></a></li>
        </ul>
      </div>
    </div>
    <br class="clear" />

  
    <%if @e==0 %>
    <p align="center" class="mailOK">Arkadasina, Borc Ekstresi E-mail ile gonderildi !  </p>
   <%@e=3%> 
   <%end%>
   <%if @e==1 %>
   <%@e=3%>
    <p align="center" class="mailOK">Arkadasin twitter'da rezil edildi :)  </p>
    <%end%>


  </div>
</div>
<div class="wrapper col5">
  <div id="footer">
    <h2>Borc Bakiyesi</h2>
    <table summary="Summary Here" cellpadding="0" cellspacing="0">
      <thead>
        <tr>
          <th>Miktar</th>
          <th>Durum</th>
          <th>Verdigim Tarih</th>
          <th>Vade Tarihi</th>
          <th colspan="2">Islemler</th>
        </tr>
      </thead>
     <%a=1%>
     <tbody>
        <% @credit.each do |credit| %>
 
        
        <%if a==1%>
        <tr class="light">
          <%a=0%>
          <%else%>
          <tr class="dark">
            <%a=1%>
            <%end%>
          <td><%= credit.miktar %><%=" TL"%></td>
          <%if credit.durum == "not_paid"%>
  
          <td><%= "Odenmedi" %></td>
            <% else %>
  
         <td> <%= "Odendi" %></td>
          <%end%>

          
          <td><%= credit.ver_tarih.to_date() %></td>
          <td><%= credit.vade_tarih.to_date() %></td>
          <td><%= link_to 'Duzenle', edit_credit_path(credit) %> </td>
          <td><%= link_to '  Borcu Sil', credit, :confirm => 'Borcunu odedi mi ?', :method => :delete %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <br class="clear" />
  </div>
</div>