config/routes.rb
Tefeci::Application.routes.draw do
  resources :credits

  
  
  
  resources :users

  resources :friends

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/tweets" => "tweets#create", :as => :create
  match "/friends/:id/email" => "friends#email", :as => :email
  match "/odenen/index" => "odenen#index"
  match "/odenmeyen/index" => "odenmeyen#index"
root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController   
 
  
  def index  
                                                            
  end                                                              
 
        
  
end        

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
       

      <%if current_user%>
<div class="wrapper col5">
  <div id="latest">
    <ul>
      <li>
        <h2>Borc Takibi</h2>
        <p class="imgholder"><img src="images/asd.png" alt="image-1" /></p>
        <p>Kime , ne zaman , ne kadar borc veridn hatirlamiyor musun ? Borclarinin takibi artik cok daha kolay. Sende.... <a href="<%=friends_path%>">Dahasi &raquo;</a></p>
      </li>
      <li>
        <h2>Borc Analizleri</h2>
        <p class="imgholder"><img src="images/Untitled_edited-1.jpg" alt="image-2" /></p>
        <p>Vergin borclarin hesabini artik tutamiyorsun. Gelirinden cok verdigin borclarin gideri var. Kimler gununde oduyor kimler...  <a href="">Dahasi &raquo;</a></p>
      </li>
      <li class="last">
        <h2>Sosyal Medya ve Email</h2>
        <p class="imgholder"><img src="images/Untitled.png" alt="image-3" /></p>
        <p>Borclarini odemeyen arkadaslarin artik cok canini sikmaya basladi. O zaman onlarin bu nankorluklerini sosyal medyada paylas herkes onun ne mal oldugunu ogrensin.... <a href="">Dahasi &raquo;</a></p>
      </li>
    </ul>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p><br class="clear" />
    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  </div>
  
  <p>&nbsp;</p>
</div>


       <%else%>
        <div class="wrapper col5">
  <div id="latest">
    <ul>
      <li>
        <h2>Borc Takibi</h2>
        <p class="imgholder"><img src="images/asd.png" alt="image-1" /></p>
        <p>Kime , ne zaman , ne kadar borc veridn hatirlamiyor musun ? Borclarinin takibi artik cok daha kolay. Sende.... <a href="/auth/twitter">Dahasi &raquo;</a></p>
      </li>
      <li>
        <h2>Borc Analizleri</h2>
        <p class="imgholder"><img src="images/Untitled_edited-1.jpg" alt="image-2" /></p>
        <p>Vergin borclarin hesabini artik tutamiyorsun. Gelirinden cok verdigin borclarin gideri var. Kimler gununde oduyor kimler...  <a href="#">Dahasi &raquo;</a></p>
      </li>
      <li class="last">
        <h2>Sosyal Medya ve Email</h2>
        <p class="imgholder"><img src="images/Untitled.png" alt="image-3" /></p>
        <p>Borclarini odemeyen arkadaslarin artik cok canini sikmaya basladi. O zaman onlarin bu nankorluklerini sosyal medyada paylas herkes onun ne mal oldugunu ogrensin.... <a href="#">Dahasi &raquo;</a></p>
      </li>
    </ul>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p><br class="clear" />
    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  </div>
  <div id="container">
   <p align="center" class="deneme"> <span class="d"><span class="deneme">Uygulama tamamen ucretsiz olup kullanmak icin tek ihtiyaciniz  bir <a href="https://twitter.com/signup"><img src="images/Untitled-1.png" width="131" height="26" alt="image-go-twitter"/></a>hesabidir..</span></span></p>
<p align="center"><a href="/auth/twitter"><img src="images/connect-with-twitter.png" width="253" height="50" alt="image-twitter-login" /></p>
  </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</div>
   <%end%>

   