config/routes.rb
Tefeci::Application.routes.draw do
  resources :credits

  
  
  
  resources :users

  resources :friends

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/tweets" => "tweets#create", :as => :create
  match "/friends/:id/email" => "friends#email", :as => :email
  match "/odenen/index" => "odenen#index"
  match "/odenmeyen/index" => "odenmeyen#index"
root :to => "home#index"

end

app/models/odenmeyen.rb
class Odenmeyen < ActiveRecord::Base

  


end

app/controllers/odenmeyen_controller.rb
class OdenmeyenController < ApplicationController   
 before_filter :login_required
  
  def index  

  	# find by durum ve friend id olacak. friend idsini current user uid den alicak. 
  	@friend=Friend.find_by_user_id(@current_user.uid)
  	@credits=Credit.find_all_by_durum_and_friend_id("not_paid",@friend.id)
                                                            
  end                                                              
 
        
  
end        

app/helpers/odenmeyen_helper.rb
module OdenmeyenHelper
end

app/views/odenmeyen/index.html.erb
<div class="wrapper col5">
  <div id="footer">
    <h2>Bekleyen Paralarim</h2>
    <table summary="Summary Here" cellpadding="0" cellspacing="0">
      <thead>
        <tr>
          <th>Adi</th>
          <th>Soyadi</th>
          <th>Email</th>
          <th>Odenmeyen Borc Miktari</th>
          <th>Islemler</th>
        </tr>
      </thead>
     <%a=1%>
     <tbody>
        <% @credits.each do |credit| %>
            <% @friends=Friend.find(credit.friend_id)%>
        
        <%if a==1%>
        <tr class="light">
          <%a=0%>
          <%else%>
          <tr class="dark">
            <%a=1%>
            <%end%>
          <td><%= @friends.name.upcase %></td>
          <td><%= @friends.surname.upcase %></td>
          <td><%= @friends.email %></td>
           <td><%=credit.miktar%> TL</td>
          <td><p align="center"><a href="<%= friend_path(@friends)%>" >Kisiyi Goruntule</a></p></td>
         
        </tr>
        <%end%>
      </tbody>
    </table>
    <br class="clear" />
    
  </div>
</div>

  
   